#! /bin/sh
$HOME/.config/picom/launch.sh
#$HOME/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III VI

bspc config border_width         0
bspc config window_gap          30
bspc config focused_border_color "#eb3167"
bspc config active_border_color  "#eb3167"
bspc config active_border_color  "#eb3167"
bspc config normal_border_color "#eb3167"
bspc config split_ratio          16
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=on
xrandr --output eDP-1 --off
#feh --bg-scale ~/Pictures/nasa.png
feh --bg-scale ~/Pictures/main.jpeg
#feh --bg-scale ~/Pictures/wred.jpg
#feh --bg-scale ~/Pictures/31.jpg
#feh --bg-tile ~/Pictures/fwblue.png
#xsetroot -solid "#131313"
#picom --experimental-backends &
